apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-elasticsearch-data
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
