apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-cluster
  namespace: elasticsearch
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/component: database
spec:
  version: 9.1.3
  nodeSets:
  - name: elasticsearch-nodeset
    count: 1
    podTemplate:
      spec:
        containers:
          - name: elasticsearch
            env:
            - name: "discovery.type"
              value: "single-node"
            volumeMounts:
            - name: roles
              mountPath: /usr/share/elasticsearch/config/roles.yml
              subPath: roles.yml
            - name: roles
              mountPath: /usr/share/elasticsearch/config/users_roles
              subPath: users_roles
            resources:
              requests:
                memory: 2Gi
        volumes:
        - name: roles
          configMap:
            name: roles
    config:
      node.roles: ["master", "data"]
      node.store.allow_mmap: false  # otherwise need to set Linux kernel setting vm.max_map_count=262144
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
        labels:
          app.kubernetes.io/name: elasticsearch
          app.kubernetes.io/component: database
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: sc-elasticsearch-data
